# #Simple Array

In [93]:
#Simple array

import numpy as np
n1 = [1,2,3,4]
np.array(n1)

array([1, 2, 3, 4])

# #Two Dimensional Array

In [3]:
#Two Dimensional array

import numpy as np
n2 = ([[1,2,3,4],[4,3,2,1]])
np.array(n2)


array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

# #Zeros

In [4]:
#Zeros

import numpy as np
n3=np.zeros((5,5))
print(n3)
print(n3.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


# #Number of Dimension (ndim)

In [88]:
#No. off array

import numpy as np
n4=np.full((4,4),10)
print(n4.ndim)

2


# #Range of Array 01

In [ ]:
#Range of array

l = []
for i in range (1,5):
    int_1 = input ("enter :")
    l.append(int_1)

print(np.array(l))


['10' '12' '14' '16']


# #Range of Array 02

In [ ]:
#Range of array

l = []
for i in range (1,5):
    int_1 = input ("enter :")
    l.append(int_1)

print(np.array(l))

['10' '11' '12' '13']


# #Two Dimensional Array, Number of dimensiona

In [1]:
#Two dimensional array, No. of dimensiona

import numpy as np
x = np.array([[1,2,3,4],[4,3,2,1]])
print(x)
print(x.ndim)  

[[1 2 3 4]
 [4 3 2 1]]
2


# #Ones element Array 01

In [7]:
#Ones element array

import numpy as np
n3=np.ones((5,5))
n3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# #Ones element Array 02

In [8]:
#Ones element array

import numpy as np
ar_one = np.ones((4,5))
print(ar_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# #Empty Array

In [92]:
#Empty array

ar_em=np.empty((2,3))
print(ar_em)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.42420209e-306 1.89146896e-307 7.56571288e-307]]


# #Range Array

In [10]:
#Range array

ar_rn=np.arange(8)
print(ar_rn)

[0 1 2 3 4 5 6 7]


# #Diagonal Element 01

In [13]:
#Diagonal

ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# #Diagonal Element 02

In [14]:
#Diagonal

ar_dia=np.eye(4,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# #Linspace 01

In [15]:
#Linspace

ar_lin=np.linspace(0,18,num=4)
print(ar_lin)

[ 0.  6. 12. 18.]


# #Linspace 02

In [16]:
#Linspace

ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# #Random

In [17]:
#Random
#Rand()

import numpy as np
x=np.random.rand(5)
print(x)

[0.16215256 0.10475624 0.48397308 0.39661836 0.13005135]


In [18]:
#Rand()
x1=np.random.rand(2,4)
print(x1)

[[0.65627667 0.00468998 0.36945915 0.56875003]
 [0.03433493 0.95745862 0.9610067  0.7543736 ]]


In [19]:
#Randn()
x2=np.random.randn(5)
print(x2)


[ 1.42148515 -0.20839213  1.91936075  1.38102239 -0.62686467]


In [20]:
#Ranf()
x3=np.random.ranf(4)
print(x3)

[0.37257642 0.06327388 0.97687201 0.66630034]


In [21]:
#Randint()
x4=np.random.randint(5,15,5)
print(x4)

[12 14  5 11 12]


# #Data Type

In [22]:
#Data Type

import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10])
print("Data Type:",x.dtype)

Data Type: int32


In [23]:
#Dtype
x1=np.array([1.2,1.3,1.4,1.5])
print("Data Type:",x1.dtype)

Data Type: float64


In [24]:
#Dtype
x2=np.array(["A","B","C","D"])
print("Data Type:",x2.dtype)

Data Type: <U1


In [25]:
#Dtype
x3=np.array(["A","B",1,2])
print("Data Type:",x3.dtype)

Data Type: <U11


In [26]:
#Dtype
x4=np.array([1,2,3,4,])
print("Data Type:",x4.dtype)

Data Type: int32


In [27]:
#Dtype
x4=np.array([1,2,3,4,],dtype=np.int8)
print("Data Type:",x4.dtype)

Data Type: int8


In [28]:
#Dtype
x4=np.array([1,2,3,4,],dtype=np.int8)
print("Data Type:",x4.dtype)
print(x4)

Data Type: int8
[1 2 3 4]


In [29]:
#Dtype
x5=np.array([1,2,3,4,],dtype="f")
print("Data Type:",x5.dtype)
print(x5)

Data Type: float32
[1. 2. 3. 4.]


In [30]:
#Dtype
x6=np.array([1,2,3,4,])
new=np.float32(x6)

print("Data Type:",x6.dtype)
print("Data Type:",new.dtype)

print(x6)
print(new)

Data Type: int32
Data Type: float32
[1 2 3 4]
[1. 2. 3. 4.]


# #Arithmetic Operation

In [31]:
#Arithmetic Operation
#add
import numpy as np
x=np.array([1,2,3,4])
xadd= x+3
print(xadd)

[4 5 6 7]


In [32]:
#add
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
xadd= x1+x2
print(xadd)


[2 4 6 8]


In [33]:

#2d Array
#add
x3=np.array([[1,2,3,4],[1,2,3,4]])
x4=np.array([[1,2,3,4],[1,2,3,4,]])

print(x3)
print()
print(x4)
print()

xadd= x3+x4
print(xadd)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [34]:
#sub
x=np.array([1,2,3,4])
xsub= x-3
print(xsub)

[-2 -1  0  1]


In [35]:

#sub
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
xsub= x1-x2
print(xsub)


[0 0 0 0]


In [36]:
#2D Array
#sub
x3=np.array([[1,2,3,4],[1,2,3,4]])
x4=np.array([[1,2,3,4],[1,2,3,4,]])

print(x3)
print()
print(x4)
print()

xsub= x3-x4
print(xsub)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


In [37]:
#mul
x=np.array([1,2,3,4])
xmul= x*3
print(xmul)

[ 3  6  9 12]


In [38]:
#mul
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
xmul= x1*x2
print(xmul)


[ 1  4  9 16]


In [39]:
#2D Array
#mul
x3=np.array([[1,2,3,4],[1,2,3,4]])
x4=np.array([[1,2,3,4],[1,2,3,4,]])

print(x3)
print()
print(x4)
print()

xmul= x3*x4
print(xmul)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [40]:
#mod
x=np.array([1,2,3,4])
xmod= x%3
print(xmod)

[1 2 0 1]


In [41]:
#mod
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
xmod= x1%x2
print(xmod)

[0 0 0 0]


# #Arithmetic Function

In [42]:
#Arithmetic Function
#minimum
import numpy as np
x=np.array([1,2,3,4])

print("min: ", np.min(x))

min:  1


In [43]:
#maximum
import numpy as np
x=np.array([1,2,3,4])

print("max: ", np.max(x))

max:  4


In [44]:
#argmin
import numpy as np
x=np.array([1,2,3,4])

print("min: ", np.min(x),np.argmin(x))

min:  1 0


In [45]:
#argmax
import numpy as np
x=np.array([1,2,3,4])

print("max: ", np.max(x),np.argmax(x))

max:  4 3


In [46]:
#sqrt
import numpy as np
x=np.array([1,2,3,4])

print("sqrt:",np.sqrt(x))

sqrt: [1.         1.41421356 1.73205081 2.        ]


In [47]:
#sin
#cos
import numpy as np
x=np.array([1,2,3,4])

print("sin:",np.sin(x))
print("cos:",np.cos(x))

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [48]:
#cumsum
import numpy as np
x=np.array([1,2,3,4])

print("cumsum:",np.cumsum(x))

cumsum: [ 1  3  6 10]


# #Shape

In [49]:
#Shape

import numpy as np
x=np.array([[1,2,3,4],[1,2,3,4,]])
print(x)
print()
print(x.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


# #Reshape

In [50]:
#Reshape
x1=np.array([1,2,3,4,5,6])
print(x1)
print(x1.ndim)

print()

x2=x1.reshape(3,2)

print(x2)
print(x2.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [51]:
#Reshape
#one to three to one

import numpy as np
x1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x1)
print(x1.ndim)

print()

x2=x1.reshape(2,3,2)

print(x2)
print(x2.ndim) 

print()

one = x2.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [52]:
#Shape and Reshape
x=np.array([[1],[2],[3],[4],[5],[6]])
print(x)
print(x.shape)
print()
print(x.reshape(2,3))
print(x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)

[[1 2 3]
 [4 5 6]]
(6, 1)


# #Broadcast

In [53]:
#Broadcast Error
import numpy as np
x=np.array([1,2,3,4])
x1=np.array([1,2,3])
print(x+x1)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [54]:
#Broadcast Learn
import numpy as np
x=np.array([1,2,3,4])
x1=np.array([1,2,3,4])
print(x+x1)

[2 4 6 8]


In [55]:
import numpy as np

x=np.array([1,2,3])
print(x.shape)
print()
print(x)
print()

x1=np.array([[1],[2],[3]])
print(x1.shape)
print()
print(x1)
print()

print(x+x1)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# #Indexing

In [56]:
#Indexing
#1D
import numpy as np
x=np.array([1,2,3,4])
#           0,1,2,3
#          -4,-3,-2,-1   
print("index ele:",x[1])
print("index ele:",x[-2])

index ele: 2
index ele: 3


In [57]:
#indexing
#2D
x=np.array([[1,2,3],[4,5,6]]) 
print(x)
print(x.ndim)
print()

print("index ele:",x[1,1])

[[1 2 3]
 [4 5 6]]
2

index ele: 5


In [58]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)
print(x.ndim)

print("index ele:",x[0,1,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
index ele: 6


#  #Slicing

In [2]:
#Slicing

import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print()
print("2 to 5:",x[1:5])
print("2 to End:",x[1:])
print("start to 5:",x[:5])
print("start to End:",x[:])
print("stop:",x[::2])

[1 2 3 4 5 6]

2 to 5: [2 3 4 5]
2 to End: [2 3 4 5 6]
start to 5: [1 2 3 4 5]
start to End: [1 2 3 4 5 6]
stop: [1 3 5]


In [60]:
#slicing
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1)
print()

print("1 to 9:", x1[0,1:])
print("1 to 9:", x1[1,1:])
print("1 to 9:", x1[2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1 to 9: [2 3]
1 to 9: [5 6]
1 to 9: [8 9]


# #Iteration

In [61]:
#Iteration

import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print()
for i in x :
    print(i)

[1 2 3 4 5 6]

1
2
3
4
5
6


In [62]:
#Iteration for 2D
import numpy as np
x=np.array([[1,2,3,4],[1,2,3,4]])
print(x)

print()
 
for j in x:
    print(j)

print()

for k in x:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [63]:
#Iteration for 3D 1st method
import numpy as np
x=np.array([[[6,5,4],[3,2,1]]])
print(x)
print(x.ndim)
print()
    
print()

for s in x:
    for p in s:
        for r in p:
            print(r)


[[[6 5 4]
  [3 2 1]]]
3


6
5
4
3
2
1


In [64]:
#Iteration for 3D 2nd method
import numpy as np
x=np.array([[[6,5,4],[3,2,1]]])
print(x)
print(x.ndim)
print()

for i in np.nditer(x):
    print(i)    



[[[6 5 4]
  [3 2 1]]]
3

6
5
4
3
2
1


# #Copy vs View

In [65]:
#COPY vs VIEW

#Copy vs View #01
import numpy as np
x= np.array([1,2,3,4])
co=x.copy()
print("x:",x)
print("copy:",co)

x: [1 2 3 4]
copy: [1 2 3 4]


In [66]:
#Copy vs View #02
x=np.array([4,3,2,1])
vi=x.view()
print("x:",x)
print("view:",vi)

x: [4 3 2 1]
view: [4 3 2 1]


In [67]:
#Copy vs View #03
import numpy as np
x= np.array([1,2,3,4])
co=x.copy()
x[1]=40
print("x:",x)
print("copy:",co)

x: [ 1 40  3  4]
copy: [1 2 3 4]


In [68]:
#Copy vs View #04
x=np.array([4,3,2,1])
vi=x.view()
x[1]=40
print("x:",x)
print("view:",vi)

x: [ 4 40  2  1]
view: [ 4 40  2  1]


# #Joining

In [69]:
#Join Array
#01 1D (concatenate)
import numpy as np
x=np.array([1,2,3,4])
x1=np.array([5,6,7,8])

ar=np.concatenate((x,x1))

print(ar)


[1 2 3 4 5 6 7 8]


In [70]:
#Join Array
#01 1D (Stack)
import numpy as np
x=np.array([1,2,3,4])
x1=np.array([5,6,7,8])

ar=np.stack((x,x1),axis=0) #0
ar1=np.stack((x,x1),axis=1) #1
ar2=np.hstack((x,x1)) #row
ar3=np.vstack((x,x1)) #column
ar4=np.dstack((x,x1)) #hight

print(ar)
print()
print(ar1)
print()
print(ar2)
print()
print(ar3)
print()
print(ar4)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [71]:
#Join Array
#02 2D (concatenate)
x=np.array([[1,2],[3,4]])
x1=np.array([[5,6],[7,8]])

ar1=np.concatenate((x,x1),axis=0)
ar=np.concatenate((x,x1),axis=1)


print(x)
print()
print(x1)
print()
#axis 0
print(ar1)
print()
#axis 1
print(ar)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
#Join Array
#02 2D (stack)
x=np.array([[1,2],[3,4]])
x1=np.array([[5,6],[7,8]])

ar=np.stack((x,x1),axis=0)
ar1=np.stack((x,x1),axis=1)

print(ar1)



[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


# #Spliting

In [95]:
#Split Array
#01
import numpy as np
x= np.array([1,2,3,4,5])
print(x)
print()
print(ar[0])
print(ar[1])
print(ar[2])
print()
ar=np.array_split(x,3)
print(ar)

[1 2 3 4 5]

[[1 2 3]]
[[4 5 6]]
[]

[array([1, 2]), array([3, 4]), array([5])]


In [74]:
#Split Array
#02
x= np.array([[1,2,3],[4,5,6]])
print(x)
print()
ar=np.array_split(x,3)
print(ar)

[[1 2 3]
 [4 5 6]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


# #Searching

In [75]:
#Search

import numpy as np
x=np.array([1,2,5,4,5,6,5,8])
#index      0,1,2,3,4,5,6,7
var=np.where (x==5)
var1=np.where ((x%2)==0)
print("(x==5):",var)
print()
print("(x%2)==0):",var1) 

(x==5): (array([2, 4, 6], dtype=int64),)

(x%2)==0): (array([1, 3, 5, 7], dtype=int64),)


# #Sorting

In [76]:
#Sort (Number)
#1D Array
import numpy as np
x=np.array([4,2,3,1,5,8,7,6,9])
#index      0,1,2,3,4,5,6,7,8

print(np.sort(x))

[1 2 3 4 5 6 7 8 9]


In [77]:
#Sort (Number)
#2D Array
import numpy as np
x=np.array([[4,2,3],[1,5,8],[7,6,9]])
#index       0,1,2,  3,4,5,  6,7,8

print(np.sort(x))

[[2 3 4]
 [1 5 8]
 [6 7 9]]


In [78]:
#Sort (String)

import numpy as np
x=np.array(["c","d","b","a","f","g","e","k","h"])
#index       0,  1,  2,  3,  4,  5,  6,  7,  8

print(np.sort(x))

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'k']


# #Shuffle

In [79]:
#Shuffle
import numpy as np
x=np.array([1,2,3,4,5])
np.random.shuffle(x)
print(x)

[5 1 2 4 3]


# #Unique

In [2]:
#Unique
import numpy as np
x=np.array([1,2,3,4,2,5,6,7,8,2])
var=np.unique(x,return_index=True,return_counts=True)
print(var)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 5, 6, 7, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1, 1], dtype=int64))


# #Resize

In [1]:
#Resize
import numpy as np
x=np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))
y1=np.resize(x,(3,2))
print(y)
print()
print(y1)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


# #Insert

In [17]:
#Insert
#in 1D array
import numpy as np
x=np.array([1,2,3,4])
# index     0,1,2,3
print(x)
print(x.dtype)
print(type(x))
y=np.insert(x,2,5)
print()
print(y)
print()
y1=np.insert(x,(2,4),5)
print(y1)

[1 2 3 4]
int32
<class 'numpy.ndarray'>

[1 2 5 3 4]

[1 2 5 3 4 5]


In [28]:
#Insert
#in 2D array
import numpy as np
x=np.array([[1,2,3],[4,5,6]])

y=np.insert(x,2,7,axis=0)
print(y)
print()
y1=np.insert(x,2,(7,8,9),axis=0)
print(y1)
print()
y=np.insert(x,2,7,axis=1)
print(y)



[[1 2 3]
 [4 5 6]
 [7 7 7]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 7 3]
 [4 5 7 6]]


# #Delete

In [31]:
#Delete

import numpy as np
x=np.array([1,2,3,4])
print(x)
d=np.delete(x,2)
print(d)

[1 2 3 4]
[1 2 4]


# #Matrix

In [34]:
#Matrix

import numpy as np
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print(type(x))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [38]:
#Matrix (Addition Operation)
x=np.matrix([[1,2,3],[4,5,6]])
x1=np.matrix([[1,2,3],[4,5,6]])

print(x)
print(type(x))
print()
print(x+x1)

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
#Matrix (Subtraction Operation)
x=np.matrix([[1,2,3],[4,5,6]])
x1=np.matrix([[1,2,3],[4,5,6]])

print(x)
print(type(x))
print()
print(x-x1)

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>

[[0 0 0]
 [0 0 0]]


In [6]:
#Matrix (Multiplication Operation)
import numpy as np
x=np.matrix([[1,2],[4,5]])
x1=np.matrix([[1,2],[4,5]])

print(x)
print(type(x))
print()
print(x*x1)
print()
print(x.dot(x1))

[[1 2]
 [4 5]]
<class 'numpy.matrix'>

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


# #Matrix Function in Numpy Arrays  

In [8]:
#Transpose
import numpy as np
x= np.matrix([[1,2,3],[5,6,7]])
print(x)
print()
print(np.transpose(x))
print()
print(x.T)

[[1 2 3]
 [5 6 7]]

[[1 5]
 [2 6]
 [3 7]]

[[1 5]
 [2 6]
 [3 7]]


In [14]:
#Swapaxes
import numpy as np
x= np.matrix([[1,2,3],[5,6,7]])
print(x)
print()
print(np.swapaxes(x,0,1))

[[1 2 3]
 [5 6 7]]

[[1 5]
 [2 6]
 [3 7]]


In [20]:
#swapaxes
x=np.matrix([[1,2],[3,4]])
print(x)
print()
print(np.swapaxes(x,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [21]:
#Inverse
x=np.matrix([[1,2],[3,4]])
print(x)
print()
print(np.linalg.inv(x))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
#Power
x=np.matrix([[1,2],[3,4]])
print(x)
print()
print(np.linalg.matrix_power(x,0))
print()
print(np.linalg.matrix_power(x,2))
print()
print(np.linalg.matrix_power(x,-2))
print()
print(np.linalg.matrix_power(x,3))
print()

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]

[[ 37  54]
 [ 81 118]]



In [37]:
#Determinate
x=np.matrix([[1,2,3],[4,5,6],[7,8,1]])
print(x)
print()
print(np.linalg.det(x))

[[1 2 3]
 [4 5 6]
 [7 8 1]]

23.999999999999993
